language: go
go:
  - 1.x
install:
  - go get github.com/redbubble/go-passe
  - go get github.com/golang/dep/cmd/dep
  - make vendor
jobs:
  include:
    - name: check formatting
      script:
        - make fmt && git diff --exit-code
    - name: run tests
      script:
        - make test
